#!/usr/bin/env python3
"""
Telegram OSINT MCP Server
Uses Telethon to search global channels, scrape messages, and gather user intel.
Requires 'anon.session' file generated by auth.py.
"""

import asyncio
import logging
import os
from typing import Any, Dict, List, Optional

from telethon import TelegramClient
from telethon import functions, types as tg_types
from telethon.tl.types import Channel, User

from mcp.server import Server, NotificationOptions
from mcp.server.models import InitializationOptions
import mcp.server.stdio
import mcp.types as types

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("telegram-mcp")

# Load environment
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

API_ID = os.environ.get("TELEGRAM_API_ID") or os.environ.get("TG_API_ID")
API_HASH = os.environ.get("TELEGRAM_API_HASH") or os.environ.get("TG_API_HASH")

app = Server("telegram-mcp")
client: Optional[TelegramClient] = None

async def get_client():
    global client
    if client is None:
        if not os.path.exists("anon.session"):
            raise FileNotFoundError("Session file 'anon.session' not found. Run auth.py first.")
        if not API_ID or not API_HASH:
            raise ValueError("TELEGRAM_API_ID/TELEGRAM_API_HASH (or TG_API_ID/TG_API_HASH) env vars missing.")
            
        client = TelegramClient('anon', int(API_ID), API_HASH)
        await client.connect()
        if not await client.is_user_authorized():
            raise PermissionError("Client not authorized. Run auth.py again.")
            
    return client

@app.list_tools()
async def handle_list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="search_global",
            description="Search Telegram global directory for channels, groups, and bots matching a query.",
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search term"
                    },
                    "limit": {
                        "type": "integer",
                        "default": 10
                    }
                },
                "required": ["query"]
            }
        ),
        types.Tool(
            name="get_channel_info",
            description="Get metadata and recent messages from a public channel/group.",
            inputSchema={
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
                        "description": "Channel username (e.g. 'durov')"
                    },
                    "limit_msgs": {
                        "type": "integer",
                        "default": 5
                    }
                },
                "required": ["username"]
            }
        ),
        types.Tool(
            name="search_messages",
            description="Search for keywords within a specific public channel.",
            inputSchema={
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
                        "description": "Channel username"
                    },
                    "query": {
                        "type": "string",
                        "description": "Keyword to search for"
                    },
                    "limit": {
                        "type": "integer",
                        "default": 10
                    }
                },
                "required": ["username", "query"]
            }
        )
    ]

@app.call_tool()
async def handle_call_tool(
    name: str, arguments: dict | None
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    
    try:
        tg = await get_client()
    except Exception as e:
        return [types.TextContent(type="text", text=f"❌ Auth Error: {str(e)}. Please run `python3 telegram-mcp/auth.py` to authenticate.")]

    if name == "search_global":
        query = arguments.get("query")
        limit = arguments.get("limit", 10)
        
        try:
            result = await tg(functions.contacts.SearchRequest(
                q=query,
                limit=limit
            ))
            
            # result.results contains peers
            # result.chats and result.users contain the details
            
            output = f"🔎 **Global Search Results for '{query}'**\n\n"
            
            for chat in result.chats:
                title = getattr(chat, 'title', 'Unknown')
                username = getattr(chat, 'username', 'No Username')
                participants = getattr(chat, 'participants_count', '?')
                output += f"- **{title}** (@{username})\n  Type: {'Channel' if getattr(chat, 'broadcast', False) else 'Group'}\n  Members: {participants}\n\n"
                
            for user in result.users:
                first = getattr(user, 'first_name', '')
                last = getattr(user, 'last_name', '')
                username = getattr(user, 'username', 'No Username')
                bot = getattr(user, 'bot', False)
                output += f"- **{first} {last}** (@{username})\n  Type: {'Bot' if bot else 'User'}\n\n"
                
            if not result.chats and not result.users:
                output += "No results found."
                
            return [types.TextContent(type="text", text=output)]
            
        except Exception as e:
            return [types.TextContent(type="text", text=f"❌ Search Error: {str(e)}")]

    elif name == "get_channel_info":
        username = arguments.get("username")
        limit = arguments.get("limit_msgs", 5)
        
        try:
            entity = await tg.get_entity(username)
            
            info = f"ℹ️ **Info for {username}**\n"
            info += f"ID: {entity.id}\n"
            info += f"Title: {getattr(entity, 'title', '')}\n"
            if isinstance(entity, Channel):
                info += f"Broadcast: {entity.broadcast}\n"
                info += f"Megagroup: {entity.megagroup}\n"
                # info += f"Restricted: {entity.restricted}\n"
            
            info += "\n**Recent Messages:**\n"
            async for msg in tg.iter_messages(entity, limit=limit):
                text = msg.text or "[Media/No Text]"
                date = msg.date.strftime("%Y-%m-%d %H:%M:%S")
                info += f"[{date}] {text[:100]}...\n"
                
            return [types.TextContent(type="text", text=info)]
            
        except Exception as e:
             return [types.TextContent(type="text", text=f"❌ Error: {str(e)}")]

    elif name == "search_messages":
        username = arguments.get("username")
        query = arguments.get("query")
        limit = arguments.get("limit", 10)
        
        try:
            entity = await tg.get_entity(username)
            output = f"🔎 **Searching '{query}' in {username}**\n\n"
            
            found = False
            async for msg in tg.iter_messages(entity, search=query, limit=limit):
                found = True
                text = msg.text or "[Media]"
                date = msg.date.strftime("%Y-%m-%d %H:%M:%S")
                msg_link = f"https://t.me/{username}/{msg.id}"
                output += f"🔗 [Link]({msg_link}) - {date}\n> {text[:200]}\n\n"
                
            if not found:
                output += "No matches found."
                
            return [types.TextContent(type="text", text=output)]
            
        except Exception as e:
            return [types.TextContent(type="text", text=f"❌ Error: {str(e)}")]

    else:
         return [types.TextContent(type="text", text=f"❌ Unknown tool: {name}")]

async def main():
    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="telegram-mcp",
                server_version="1.0.0",
                capabilities=app.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )

if __name__ == "__main__":
    asyncio.run(main())
